# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsoffers',
            name='parent_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_site.Categories'),
        ),
    ]
