# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20161003_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('brand_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('name', models.TextField()),
                ('body', models.TextField()),
                ('visible', models.BooleanField()),
                ('parent_category', models.ManyToManyField(to='main_site.Categories')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemsoffers',
            name='parent_category',
        ),
        migrations.DeleteModel(
            name='ItemsOffers',
        ),
    ]
