# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20161010_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
