# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20161010_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_id',
        ),
    ]
