# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=255)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
                ('annotation', models.TextField()),
                ('text', models.TextField()),
                ('visible', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 's_blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 's_brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_keywords', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('tagline', models.TextField()),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('visible', models.IntegerField()),
                ('external_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 's_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SCategoriesFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('feature_id', models.IntegerField()),
            ],
            options={
                'db_table': 's_categories_features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SComments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
                ('object_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=7)),
                ('approved', models.IntegerField()),
            ],
            options={
                'db_table': 's_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SCoupons',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('single', models.IntegerField()),
                ('usages', models.IntegerField()),
            ],
            options={
                'db_table': 's_coupons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sign', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
                ('rate_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cents', models.IntegerField()),
                ('position', models.IntegerField()),
                ('enabled', models.IntegerField()),
            ],
            options={
                'db_table': 's_currencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('free_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enabled', models.IntegerField()),
                ('position', models.IntegerField()),
                ('separate_payment', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 's_delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SDeliveryPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.IntegerField()),
                ('payment_method_id', models.IntegerField()),
            ],
            options={
                'db_table': 's_delivery_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('in_filter', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 's_features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SFeedbacks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 's_feedbacks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 's_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_id', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 's_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=6)),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 's_labels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 's_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('feature_id', models.IntegerField()),
                ('value', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 's_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SOrders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_id', models.IntegerField(blank=True, null=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method_id', models.IntegerField(blank=True, null=True)),
                ('paid', models.IntegerField()),
                ('payment_date', models.DateTimeField()),
                ('closed', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=1024)),
                ('status', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_details', models.TextField()),
                ('ip', models.CharField(max_length=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(max_length=1024)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coupon_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_code', models.CharField(max_length=255)),
                ('separate_delivery', models.IntegerField()),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 's_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SOrdersLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('label_id', models.IntegerField()),
            ],
            options={
                'db_table': 's_orders_labels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('menu_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('visible', models.IntegerField()),
                ('header', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 's_pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SPaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('currency_id', models.FloatField()),
                ('settings', models.TextField()),
                ('enabled', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 's_payment_methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('vendor_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('annotation', models.TextField()),
                ('body', models.TextField()),
                ('visible', models.IntegerField()),
                ('position', models.IntegerField()),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('featured', models.IntegerField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 's_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SProductsCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 's_products_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('variant_id', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
                ('sku', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 's_purchases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SRelatedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('related_id', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 's_related_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SSettings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 's_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('number_unp', models.CharField(max_length=14)),
                ('con_tel', models.CharField(max_length=20)),
                ('group_id', models.IntegerField()),
                ('enabled', models.IntegerField()),
                ('last_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 's_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SVariants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('sku', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('attachment', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 's_variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SVendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 's_vendors',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='parent_category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
