# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_auto_20161019_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelistmodel',
            old_name='category_id',
            new_name='category',
        ),
    ]
