# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_auto_20161020_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistmodel',
            name='articul',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
