# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0015_auto_20161020_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistmodel',
            name='articul',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
