# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_auto_20161020_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.Categories'),
        ),
        migrations.AddField(
            model_name='products',
            name='dealer',
            field=models.ForeignKey(db_column='dealer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.Dealer'),
        ),
    ]
