# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0018_auto_20161020_1648'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dealer',
            table='t_dealer',
        ),
    ]
