# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0019_auto_20161020_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
