# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0020_auto_20161031_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dealer_price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='recomend_price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rozn_price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
