# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0021_auto_20161031_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='document',
            field=models.ForeignKey(db_column='document_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.Documents'),
        ),
        migrations.AddField(
            model_name='products',
            name='document',
            field=models.ForeignKey(db_column='document_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.Documents'),
        ),
    ]
