# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0022_auto_20161108_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='document',
        ),
        migrations.AddField(
            model_name='documents',
            name='dealer',
            field=models.ForeignKey(db_column='dealer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.Dealer'),
        ),
        migrations.AlterField(
            model_name='products',
            name='dealer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
